export const ROUTES = {
  LANDING: "/",
  HOME: "/home",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  BOARDS: "/boards",
  MY_TASKS: "/tasks",
  CALENDAR: "/calendar",
  KNOWLEDGE_BASE: "/knowledge",
  AI_ASSISTANT: "/assistant",
  SETTINGS: "/settings",
  HELP: "/help",
  UNDER_DEVELOPMENT: "/under-development",
} as const;
